### PR TITLE
Add PHP 7 on Travis

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by hackzilla** [comment]
Cheers

**Comment by Soullivaneuh** [comment]
You're welcome.

But BTW, where are your test files?

**Comment by hackzilla** [comment]
I started with good intensions, but then struggled to actually test the bundle.

**Comment by hackzilla** [comment]
I've now added some basic tests

**Comment by Soullivaneuh** [comment]
:+1:

**Pull request merged**
