### PR TITLE
Allow Symfony 3

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Updated `composer.json` and add some BC code on `OptionType`.

### CODE REVIEW

**Comment by hackzilla** [comment]
Any chance you can rebase?

I'm getting "This branch has conflicts that must be resolved".

**Comment by Soullivaneuh** [comment]
Just done! :+1:

**Comment by hackzilla** [comment]
Thanks for all your contributions!

**Comment by Soullivaneuh** [comment]
Thanks! Can we please have a new tag for this one? :-)

**Comment by hackzilla** [comment]
Sure.  v1.5

**Comment by Soullivaneuh** [comment]
:+1:

**Pull request merged**
